### PR TITLE
Added missing flag for enabling bitcode

### PR DESCRIPTION
**Pull request by dev4dev**

### CODE REVIEW

**Comment by leavez** [comment]
Hi @dev4dev 

It seems `BITCODE_GENERATION_MODE=bitcode` and `OTHER_CFLAGS="-fembed-bitcode"` is doing the same thing. There should be only one flag here. 

https://stackoverflow.com/questions/34959767/whats-the-difference-between-fembed-bitcode-and-bitcode-generation-mode

**Comment by dev4dev** [comment]
@leavez I don't see where in that SO post stated that they are the same. At other posts I googled, it was mentioned that both of them are required, to include bitcode.

To be honest, I haven't tested only `BITCODE_GENERATION_MODE=bitcode` without `OTHER_CFLAGS="-fembed-bitcode"`, but `OTHER_CFLAGS="-fembed-bitcode"` only doesn't add bitcode into binary, because of that my builds failed. After adding `BITCODE_GENERATION_MODE=bitcode` now everything is ok. So these changes gave me working result

**Comment by dev4dev** [comment]
and by the way, thanks for the plugin, it saved a lot of build time, just packing Realm into a framework

**Comment by leavez** [comment]
Very glad to hear that. And sorry about the slow response as I'm too busy these days.

@X140Yu Could you take care of this?

**Comment by X140Yu** [comment]
Hi @dev4dev ,

When I try to archive some target with pod Realm inside with `OTHER_CFLAGS="-fembed-bitcode"` setting, I got an error message like this,

image

But after changing the build option to `BITCODE_GENERATION_MODE=bitcode`, the error above has gone. 

Also according to [this SO link](https://stackoverflow.com/a/34965178/6343571), it seems like only using `BITCODE_GENERATION_MODE` setting can do the work.

So could you change the setting to `BITCODE_GENERATION_MODE=bitcode` and remove the old `cflags` staff in your PR?

**Comment by dev4dev** [comment]
@X140Yu I'll try to test this on our CI soon, and will let you know the result

**Comment by grigorye** [comment]
Just in case, I can confirm that "BITCODE_GENERATION_MODE=bitcode" is a necessary change in our project. Without it "archive" action failed trying to link some app code (apparently bitcode enabled, verified it through the logs) with the framework generated by this plugin.

**Comment by vellori** [comment]
can we merge this and release? I'm available to help if needed because I use this in my project ☺️ @X140Yu

**Comment by leavez** [comment]
'OTHER_CFLAGS="-fembed-bitcode"' is removed in commit `30cbf7f1`

**Pull request merged**
