### PR TITLE
Fix a typo in the logo

### PR DESCRIPTION
**Pull request by orta**
Cocoapods -> CocoaPods 👍 

Nice work BTW, not sure if I've mentioned that before

### CODE REVIEW

**Comment by orta** [comment]
There's irony in having a typo in the title

**Comment by leavez** [comment]
First of all, a real capital 'P' should be used, instead just moving the 'p' in the logo higher. And sorry... I forget the font.

I know 'CocoaPods' is the best spell. But, IMHO, the new logo may be not the best choice, as the 3 capital letters break some visual balance. I prefer the original one.

**Comment by orta** [comment]
I'm not quite sure what you're asking me to do, do you want me to re-create the logo from scratch to fix the typo?

**Comment by leavez** [comment]
I don't think it's a good solution. I'll redesign the logo later.

 #52

**Pull request closed without merging**
